[2024-08-21T22:24:21.436+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T22:24:21.449+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker_spark_tasks.stream_to_postgres manual__2024-08-21T22:12:10.549926+00:00 [queued]>
[2024-08-21T22:24:21.454+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker_spark_tasks.stream_to_postgres manual__2024-08-21T22:12:10.549926+00:00 [queued]>
[2024-08-21T22:24:21.454+0000] {taskinstance.py:2856} INFO - Starting attempt 8 of 9
[2024-08-21T22:24:21.463+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): stream_to_postgres> on 2024-08-21 22:12:10.549926+00:00
[2024-08-21T22:24:21.469+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=614) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-21T22:24:21.469+0000] {standard_task_runner.py:72} INFO - Started process 616 to run task
[2024-08-21T22:24:21.470+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'docker_spark_tasks', 'stream_to_postgres', 'manual__2024-08-21T22:12:10.549926+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpmp8hz_sh']
[2024-08-21T22:24:21.471+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask stream_to_postgres
[2024-08-21T22:24:21.498+0000] {task_command.py:467} INFO - Running <TaskInstance: docker_spark_tasks.stream_to_postgres manual__2024-08-21T22:12:10.549926+00:00 [running]> on host 2b775d69f181
[2024-08-21T22:24:21.552+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='docker_spark_tasks' AIRFLOW_CTX_TASK_ID='stream_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T22:12:10.549926+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T22:12:10.549926+00:00'
[2024-08-21T22:24:21.553+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-21T22:24:21.553+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-21T22:24:21.553+0000] {logging_mixin.py:190} INFO - Current task name:stream_to_postgres state:running start_date:2024-08-21 22:24:21.449317+00:00
[2024-08-21T22:24:21.553+0000] {logging_mixin.py:190} INFO - Dag name:docker_spark_tasks and current dag run status:running
[2024-08-21T22:24:21.553+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T22:24:21.554+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T22:24:21.554+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec node-master /home/spark/src/spark/submit.sh stream_to_postgres.py']
[2024-08-21T22:24:21.566+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T22:24:23.209+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/spark/spark-3.5.1-bin-hadoop3/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-08-21T22:24:23.292+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/spark/.ivy2/cache
[2024-08-21T22:24:23.293+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/spark/.ivy2/jars
[2024-08-21T22:24:23.299+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2024-08-21T22:24:23.300+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2024-08-21T22:24:23.300+0000] {subprocess.py:93} INFO - org.mongodb.spark#mongo-spark-connector_2.12 added as a dependency
[2024-08-21T22:24:23.301+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-ed743f7f-a4a5-464b-9504-ee30c2bf2715;1.0
[2024-08-21T22:24:23.301+0000] {subprocess.py:93} INFO - 	confs: [default]
[2024-08-21T22:24:23.424+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.5.4 in central
[2024-08-21T22:24:23.451+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.5.0 in central
[2024-08-21T22:24:23.544+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 in central
[2024-08-21T22:24:23.612+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 in central
[2024-08-21T22:24:23.640+0000] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;3.4.1 in central
[2024-08-21T22:24:23.667+0000] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2024-08-21T22:24:23.688+0000] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.10.3 in central
[2024-08-21T22:24:23.711+0000] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;2.0.7 in central
[2024-08-21T22:24:23.740+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2024-08-21T22:24:23.777+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2024-08-21T22:24:23.816+0000] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2024-08-21T22:24:23.846+0000] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2024-08-21T22:24:23.867+0000] {subprocess.py:93} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2024-08-21T22:24:23.883+0000] {subprocess.py:93} INFO - 	found org.mongodb.spark#mongo-spark-connector_2.12;10.3.0 in central
[2024-08-21T22:24:36.714+0000] {subprocess.py:93} INFO - 	found org.mongodb#mongodb-driver-sync;4.8.2 in central
[2024-08-21T22:24:36.716+0000] {subprocess.py:93} INFO - 	[4.8.2] org.mongodb#mongodb-driver-sync;[4.8.1,4.8.99)
[2024-08-21T22:24:36.742+0000] {subprocess.py:93} INFO - 	found org.mongodb#bson;4.8.2 in central
[2024-08-21T22:24:36.756+0000] {subprocess.py:93} INFO - 	found org.mongodb#mongodb-driver-core;4.8.2 in central
[2024-08-21T22:24:36.767+0000] {subprocess.py:93} INFO - 	found org.mongodb#bson-record-codec;4.8.2 in central
[2024-08-21T22:24:36.789+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 13477ms :: artifacts dl 12ms
[2024-08-21T22:24:36.790+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2024-08-21T22:24:36.790+0000] {subprocess.py:93} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2024-08-21T22:24:36.790+0000] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2024-08-21T22:24:36.790+0000] {subprocess.py:93} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2024-08-21T22:24:36.790+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2024-08-21T22:24:36.790+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2024-08-21T22:24:36.791+0000] {subprocess.py:93} INFO - 	org.apache.kafka#kafka-clients;3.4.1 from central in [default]
[2024-08-21T22:24:36.791+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 from central in [default]
[2024-08-21T22:24:36.791+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 from central in [default]
[2024-08-21T22:24:36.791+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.5.0 from central in [default]
[2024-08-21T22:24:36.791+0000] {subprocess.py:93} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2024-08-21T22:24:36.791+0000] {subprocess.py:93} INFO - 	org.mongodb#bson;4.8.2 from central in [default]
[2024-08-21T22:24:36.791+0000] {subprocess.py:93} INFO - 	org.mongodb#bson-record-codec;4.8.2 from central in [default]
[2024-08-21T22:24:36.792+0000] {subprocess.py:93} INFO - 	org.mongodb#mongodb-driver-core;4.8.2 from central in [default]
[2024-08-21T22:24:36.792+0000] {subprocess.py:93} INFO - 	org.mongodb#mongodb-driver-sync;4.8.2 from central in [default]
[2024-08-21T22:24:36.792+0000] {subprocess.py:93} INFO - 	org.mongodb.spark#mongo-spark-connector_2.12;10.3.0 from central in [default]
[2024-08-21T22:24:36.792+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.5.4 from central in [default]
[2024-08-21T22:24:36.792+0000] {subprocess.py:93} INFO - 	org.slf4j#slf4j-api;2.0.7 from central in [default]
[2024-08-21T22:24:36.792+0000] {subprocess.py:93} INFO - 	org.xerial.snappy#snappy-java;1.1.10.3 from central in [default]
[2024-08-21T22:24:36.792+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-08-21T22:24:36.792+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-08-21T22:24:36.793+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-08-21T22:24:36.793+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-08-21T22:24:36.793+0000] {subprocess.py:93} INFO - 	|      default     |   18  |   1   |   0   |   0   ||   18  |   0   |
[2024-08-21T22:24:36.793+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-08-21T22:24:36.796+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-ed743f7f-a4a5-464b-9504-ee30c2bf2715
[2024-08-21T22:24:36.796+0000] {subprocess.py:93} INFO - 	confs: [default]
[2024-08-21T22:24:36.803+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 18 already retrieved (0kB/7ms)
[2024-08-21T22:24:36.957+0000] {subprocess.py:93} INFO - 24/08/21 19:24:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-21T22:24:37.374+0000] {subprocess.py:93} INFO - python3: can't open file '/home/spark/stream_to_postgres.py': [Errno 2] No such file or directory
[2024-08-21T22:24:37.388+0000] {subprocess.py:93} INFO - 24/08/21 19:24:37 INFO ShutdownHookManager: Shutdown hook called
[2024-08-21T22:24:37.388+0000] {subprocess.py:93} INFO - 24/08/21 19:24:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-4b75f557-d614-41ea-b7d7-df7082d11b3f
[2024-08-21T22:24:37.424+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-21T22:24:37.432+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-21T22:24:37.438+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-21T22:24:37.438+0000] {logging_mixin.py:190} INFO - Task start:2024-08-21 22:24:21.449317+00:00 end:2024-08-21 22:24:37.437702+00:00 duration:15.988385
[2024-08-21T22:24:37.438+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): stream_to_postgres> dag:<DAG: docker_spark_tasks> dagrun:<DagRun docker_spark_tasks @ 2024-08-21 22:12:10.549926+00:00: manual__2024-08-21T22:12:10.549926+00:00, state:running, queued_at: 2024-08-21 22:12:10.566226+00:00. externally triggered: True>
[2024-08-21T22:24:37.438+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2024-08-21T22:24:37.439+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=docker_spark_tasks, task_id=stream_to_postgres, run_id=manual__2024-08-21T22:12:10.549926+00:00, execution_date=20240821T221210, start_date=20240821T222421, end_date=20240821T222437
[2024-08-21T22:24:37.450+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T22:24:37.450+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 43 for task stream_to_postgres (Bash command failed. The command returned a non-zero exit code 2.; 616)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-21T22:24:37.474+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-21T22:24:37.490+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-21T22:24:37.490+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
